apiVersion: v1
kind: Service
metadata:
  name: harvester-network-webhook
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: {{ .Values.webhook.httpsPort }}
  selector:
    {{- include "harvester-network-webhook.selectorLabels" . | nindent 4 }}
  type: ClusterIP
