apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "harvester-node-manager.labels" . | nindent 4 }}
  name: {{ include "harvester-node-manager.name" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "harvester-node-manager.name" . }}
rules:
  - apiGroups: [ "node.harvesterhci.io" ]
    resources: [ "*" ]
    verbs: [ "*" ]
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get", "watch", "list", "update" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "harvester-node-manager.labels" . | nindent 4 }}
  name: {{ include "harvester-node-manager.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "harvester-node-manager.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "harvester-node-manager.name" . }}
    namespace: {{ .Release.Namespace }}