apiVersion: v2
description: vcluster - Virtual Kubernetes Clusters
home: https://vcluster.com
icon: https://static.loft.sh/branding/logos/vcluster/vertical/vcluster_vertical.svg
keywords:
  - developer
  - development
  - sharing
  - share
  - multi-tenancy
  - tenancy
  - cluster
  - space
  - namespace
  - vcluster
  - vclusters
maintainers:
  - name: LoftLabs
name: vcluster
sources:
  - https://github.com/loft-sh/vcluster
type: application
version: 0.0.0-dev
appVersion: 0.15.2
