---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "harvester-node-manager-webhook.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    {{- include "harvester-node-manager-webhook.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443