apiVersion: v1
kind: ServiceAccount
metadata:
  name: forklift-controller
  labels:
  {{- include "forklift-operator.labels" . | nindent 4 }}
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: forklift-api
  labels:
  {{- include "forklift-operator.labels" . | nindent 4 }}
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: forklift-populator-controller
  labels:
  {{- include "forklift-operator.labels" . | nindent 4 }}
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: forklift-operator
  labels:
  {{- include "forklift-operator.labels" . | nindent 4 }}
automountServiceAccountToken: true
