apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "harvester-pcidevices-controller.labels" . | nindent 4 }}
  name: pcidevices-webhook
spec:
  ports:
    - port: 8443
  publishNotReadyAddresses: true
  selector:
    {{- include "harvester-pcidevices-controller.selectorLabels" . | nindent 4 }}
