apiVersion: v1
kind: Service
metadata:
  name: pcidevices-webhook
  labels:
    {{- include "harvester-pcidevices-controller.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "harvester-pcidevices-controller.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
