apiVersion: v1
kind: Service
metadata:
  name: {{ include "harvester-load-balancer.name" . }}-webhook
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: {{ .Values.webhook.httpsPort }}
  selector:
    {{- include "harvester-load-balancer-webhook.selectorLabels" . | nindent 4 }}
  type: ClusterIP