apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: harvester
  annotations:
{{ include "harvester-csi-driver.annotations.defaultstorageclass" . | indent 4 }}
allowVolumeExpansion: true
provisioner: driver.harvesterhci.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
