apiVersion: v1
kind: Service
metadata:
  name: {{ include "harvester-vm-dhcp-controller.fullname" . }}
  labels:
    {{- include "harvester-vm-dhcp-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "harvester-vm-dhcp-controller.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "harvester-vm-dhcp-controller.fullname" . }}-webhook
  labels:
    {{- include "harvester-vm-dhcp-webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhook.service.type }}
  ports:
    - port: {{ .Values.webhook.service.port }}
      targetPort: {{ .Values.webhook.httpsPort }}
      protocol: TCP
      name: https
  selector:
    {{- include "harvester-vm-dhcp-webhook.selectorLabels" . | nindent 4 }}
