{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nvidia-driver-runtime.serviceAccountName" . }}
  labels:
    {{- include "nvidia-driver-runtime.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nvidia-driver-runtime.serviceAccountName" . }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "nvidia-driver-runtime.serviceAccountName" . }}
  labels:
  {{- include "nvidia-driver-runtime.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nvidia-driver-runtime.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "nvidia-driver-runtime.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}