apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "kubeovn-operator.labels" . | nindent 4 }}
  name: kubeovn-operator-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    {{- include "kubeovn-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "kubeovn-operator.labels" . | nindent 4 }}
  name: kubeovn-operator-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    {{- include "kubeovn-operator.labels" . | nindent 4 }}
    control-plane: controller-manager