apiVersion: management.cattle.io/v3
builtin: false
context: cluster
description: "Harvester PCIDevices Admin Role can manage all device resources on downstream Harvester cluster"
displayName: Harvester PCIDevices Admin Role
external: false
hidden: false
kind: RoleTemplate
metadata:
  name: harvester-pcidevices-admin
rules:
- apiGroups:
  - devices.harvesterhci.io
  resources:
  - pcidevices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devices.harvesterhci.io
  resources:
  - pcideviceclaims
  verbs:
  - '*'
- apiGroups:
  - harvesterhci.io
  resources:
  - addons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devices.harvesterhci.io
  resources:
  - sriovgpudevices
  - vgpudevices
  - sriovnetworkdevices
  verbs:
  - get
  - list
  - watch
  - update
  - patch
