{{- if .Values.pvcClaim.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "vm-import-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vm-import-controller.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem 
  resources:
    requests:
      storage: {{ .Values.pvcClaim.size | quote }}
{{- $storageClassName := .Values.pvcClaim.storageClassName | default .Values.pvcClaim.storageClass }}
{{- if $storageClassName }}
{{- if eq $storageClassName "-" }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ $storageClassName | quote }}
{{- end }}
{{- end }}
{{- end }}
