apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name:  {{ include "vm-import-controller.fullname" . }}-role
rules:
- apiGroups:
  - migration.harvesterhci.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
    - kubevirt.io
  resources:
    - virtualmachines
  verbs:
    - "*"
- apiGroups:
    - harvesterhci.io
  resources:
    - virtualmachineimages
  verbs:
    - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - secrets
  - persistentvolumeclaims
  verbs:
  - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vm-import-controller.fullname" . }}-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vm-import-controller.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "vm-import-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
