apiVersion: v1
kind: Service
metadata:
  name: harvester-vm-import-controller
spec:
  selector:
    {{- include "vm-import-controller.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
