apiVersion: v1
kind: Service
metadata:
  name: {{ include "vm-import-controller.fullname" . }}
spec:
  selector:
    {{- include "vm-import-controller.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
