apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: harvester-mcp-server
  name: harvester-mcp-server
  namespace: cattle-ai-agent-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harvester-mcp-server
  template:
    metadata:
      labels:
        app: harvester-mcp-server
    spec:
      serviceAccountName: harvester-mcp-cert-rotator-sa
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
        # If seLinux.enabled is set to true in values.yaml, the container will run as type rancher_aimcp_container_t.
        # Note: https://github.com/rancher/rancher-selinux policy should be installed.
        {{- if .Values.seLinux.enabled }}
        seLinuxOptions:
          type: rancher_aimcp_container_t
        {{- end }}
      volumes:
        - name: tmp-dir
          emptyDir: {}
      containers:
      - image: "{{ template "system_default_registry" . }}{{ .Values.mcp.image.repository }}:{{ .Values.mcp.image.tag }}"
        imagePullPolicy: "{{ .Values.mcp.image.pullPolicy }}"
        name: mcp-server
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        ports:
          - containerPort: 9092
        command: ["/usr/local/bin/mcp"]
        args:
          - "serve"
          - "--port"
          - "9092"
          {{- if .Values.insecureSkipTls }}
          - "--insecure"
          {{- end }}
          {{- if .Values.mcp.readOnly }}
          - "--read-only"
          {{- end }}
          {{- if .Values.log.level }}
          - "--log-level"
          - "{{ .Values.log.level }}"
          {{- end }}
        volumeMounts:
          - name: tmp-dir
            mountPath: /tmp
