apiVersion: v1
kind: Service
metadata:
  name: harvester-mcp-server
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: harvester-mcp-server
  ports:
    - port: 80
      name: http
      targetPort: 9092
      protocol: TCP
    - port: 443
      name: https
      targetPort: 9092
      protocol: TCP
  type: ClusterIP