apiVersion: v1
kind: Secret
metadata:
  name: rancher-init
  namespace: rancher-k3k
stringData:
  manifests.yaml: |-
    apiVersion: helm.cattle.io/v1
    kind: HelmChart
    metadata:
      name: cert-manager
      namespace: kube-system
    spec:
      createNamespace: true
      targetNamespace: cert-manager
      repo: https://charts.jetstack.io
      chart: cert-manager
      version: {{ .Values.certManagerVersion }}
      helmVersion: v3
      set:
        installCRDs: "true"
    ---
    apiVersion: helm.cattle.io/v1
    kind: HelmChart
    metadata:
      name: rancher
      namespace: kube-system
    spec:
      createNamespace: true
      targetNamespace: cattle-system
      repo: https://releases.rancher.com/server-charts/latest
      chart: rancher
      version: {{ .Values.rancher.version }}
      set:
        extraEnv[0].name: "CATTLE_IMPORTED_CLUSTER_VERSION_MANAGEMENT"
        extraEnv[0].value: "\"false\""
        priorityClassName: system-cluster-critical
        ingress.tls.source: rancher
        hostname: {{ .Values.rancher.hostname | quote }}
        replicas: {{ .Values.rancher.replicas }}
        global.cattle.psp.enabled: "false"
        bootstrapPassword: {{ .Values.rancher.bootstrapPassword | quote }}
      helmVersion: v3
---
apiVersion: k3k.io/v1beta1
kind: Cluster
metadata:
  name: rancher-k3k-cluster
  namespace: rancher-k3k
spec:
  mode: shared
  servers: {{ .Values.k3kCluster.servers }}
  agents: {{ .Values.k3kCluster.agents }}
  sync:
    ingresses:
      enabled: true
  secretMounts:
    - secretName: rancher-init
      mountPath: /var/lib/rancher/k3s/server/manifests/rancher-init
  persistence:
    type: dynamic
    storageClassName:  {{ .Values.k3kCluster.storageClassName }}