apiVersion: v1
kind: Namespace
metadata:
  name: rancher-k3k
---
apiVersion: v1
kind: Namespace
metadata:
  name: rancher-k3k-init
---
apiVersion: v1
kind: Secret
metadata:
  name: rancher-init
  namespace: rancher-k3k-init
stringData:
  manifests.yaml: |-
    apiVersion: v1
    kind: Namespace
    metadata:
      name: cattle-system
    ---
    apiVersion: v1
    kind: Namespace
    metadata:
      name: cert-manager
      labels:
        certmanager.k8s.io/disable-validation: "true"
    ---
    apiVersion: helm.cattle.io/v1
    kind: HelmChart
    metadata:
      name: cert-manager
      namespace: kube-system
    spec:
      targetNamespace: cert-manager
      repo: https://charts.jetstack.io
      chart: cert-manager
      version: {{ .Values.certManagerVersion }}
      helmVersion: v3
      set:
        installCRDs: "true"
    ---
    apiVersion: helm.cattle.io/v1
    kind: HelmChart
    metadata:
      name: rancher
      namespace: kube-system
    spec:
      targetNamespace: cattle-system
      repo: https://releases.rancher.com/server-charts/latest
      chart: rancher
      version: {{ .Values.rancher.version }}
      set:
        priorityClassName: system-cluster-critical
        ingress.tls.source: rancher
        hostname: {{ .Values.rancher.hostname | quote }}
        replicas: {{ .Values.rancher.replicas }}
        global.cattle.psp.enabled: "false"
        bootstrapPassword: {{ .Values.rancher.bootstrapPassword | quote }}
      helmVersion: v3
---
apiVersion: k3k.io/v1beta1
kind: Cluster
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
  name: rancher-k3k-cluster
  namespace: rancher-k3k
spec:
  mode: shared
  servers: {{ .Values.k3kCluster.servers }}
  agents: {{ .Values.k3kCluster.agents }}
  version: {{ .Values.k3kCluster.version | quote }}
  sync:
    ingresses:
      enabled: true
  addons:
    - secretRef: rancher-init
      secretNamespace: rancher-k3k-init
  persistence:
    type: dynamic
    storageClassName:  {{ .Values.k3kCluster.storageClassName }}