apiVersion: v2
name: harvester-upgrade-manager
description: A Helm chart to distribute harvester-upgrade-manager
type: application

version: 0.0.0-dev
appVersion: "v0.1.0"

keywords:
  - kubernetes
  - operator

annotations:
  kubebuilder.io/generated-by: kubebuilder

maintainers:
  - name: harvester
