apiVersion: v2
name: harvester-upgrade-manager
description: A Helm chart to distribute harvester-upgrade-manager
type: application

version: 1.8.0-rc6.r2
appVersion: "v1.8.0-rc6.r2"

keywords:
  - kubernetes
  - operator

annotations:
  kubebuilder.io/generated-by: kubebuilder

maintainers:
  - name: harvester
